# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nomad-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nomad-App

pod 'SegementSlide','2.2.3'
pod 'Firebase','6.11.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'FirebaseUI/Storage'
pod 'Firebase/Messaging'
pod 'NotificationBannerSwift', '~> 3.0.0'
pod 'SVProgressHUD','2.2.5'
pod 'PKHUD', '~> 5.0'
pod 'LicensePlist'
pod 'Google-Mobile-Ads-SDK'
pod 'MXParallaxHeader'
pod 'CropViewController'
pod "KRProgressHUD"
pod "LBTAComponents"
pod 'KMPlaceholderTextView', '~> 1.4.0'

end
